myapp/urls.py
from django.urls import include, path

from .views import add_product, index, products, products_details,update_product,delete_product

app_name='myapp'

urlpatterns = [
    path('',index),
    path('products',products,name='products'),
    path('products/<int:id>',products_details,name='products_details'),
    path('products/add',add_product,name='add_product'),
    path('products/update/<int:id>',update_product,name='update_product'),
    path('products/delete/<int:id>',delete_product,name='delete_product'),
    
]

mysite/urls.py
from xml.etree.ElementInclude import include

from django.conf import Settings, settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from myapp.views import index
from mysite import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp/',index),
    path('myapp/',include('myapp.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
    path('users/',include('users.urls')),
    
]

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import register,profile,create_profile
from django.contrib.auth import views as authentication_views

app_name = 'users'



urlpatterns = [
    path('register/',register,name='products'),
    path('login/',authentication_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',authentication_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
    path('profile/',profile,name='profile '),
    path('createprofile/',create_profile,name='createprofile'),
]

myapp/models.py
from django.db import models
from django.contrib.auth.models import User


class product(models.Model):
     def __str__(self):
          return self.name     
     name = models.CharField(max_length=100,unique=True)
     price = models.FloatField()
     description = models.CharField(max_length=200)
     details = models.CharField(max_length=2000,blank=True)
     image = models.ImageField(blank=True,upload_to='images')
     seller = models.ForeignKey(User,on_delete=models.CASCADE)

users/models.py
from django.db import models 
from django.contrib.auth.admin import User


class Profile(models.Model):
    def __str__(self):
        return self.user.username
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    image=models.ImageField(blank=True,upload_to='profile_pics')
    contact_number=models.CharField(max_length=10)
    

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms


class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True,widget=forms.EmailInput(attrs={'class':'input input-bordered input-primary w-full px-4 py-2 mt-2 border rounded-md focus:outline-none focus:ring-1 focus:ring-blue-600','placeholder':'Enter your email address'}))
    username = forms.CharField(required=True,widget=forms.TextInput(attrs={'class':'input input-bordered input-primary w-full px-4 py-2 mt-2 border rounded-md focus:outline-none focus:ring-1 focus:ring-blue-600 ','placeholder':'Enter your Name'}))
    password1 = forms.CharField(required=True,widget=forms.PasswordInput(attrs={'class':'input input-bordered input-primary w-full px-4 py-2 mt-2 border rounded-md focus:outline-none focus:ring-1 focus:ring-blue-600'}))
    password2 = forms.CharField(required=True,widget=forms.TextInput(attrs={'class':'input input-bordered input-primary w-full px-4 py-2 mt-2 border rounded-md focus:outline-none focus:ring-1 focus:ring-blue-600'}))
    
    class Meta:
        model = User
        fields = {'email','username','password1','password2',}

myapp/views.py
from multiprocessing import context

from django.http import HttpRequest, HttpResponse
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from myapp.models import product


def index(request):
    d = {
        "name":"arun",
        "age":30,
    }
    
    li = ["allen","sreerag","alwin","justin","allu","hari"]
    
    for i in range (0,10):
        print(i)
        
    context ={'li': li}
     
    return render(request,'myapp/index.html',context=context)



def products(request):
    p = product.objects.all()
    context={'products':p}
    return render(request,'myapp/products.html',context=context)

@login_required
def products_details(request,id):
    p = product.objects.get(id=id)
    context={'p':p}
    return render(request,'myapp/products_details.html',context=context)

def add_product(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        price = request.POST.get('price')
        desc = request.POST.get('desc')
        details = request.POST.get('details')
        image = request.FILES['upload']
        p=product(name=name,price=price,description=desc,image=image)
        p.save()
        
        return redirect('/myapp/products')
        
    return render(request,'myapp/add_product.html')

def update_product(request,id):
    p = product.objects.get(id=id)
    context = {'p':p}
    
    
    if request.method == 'POST':
        p.name = request.POST.get('name')
        p.price = request.POST.get('price')
        p.description = request.POST.get('desc')
        p.details = request.POST.get('details')
        try:
            p.image = request.FILES['upload']
        except:
            pass
        p.save()
        
        return redirect('/myapp/products')
        
    return render(request,'myapp/update_product.html',context=context)

def delete_product(request,id):
    p = product.objects.get(id=id)
    context = {'p':p}
    
    if request.method == 'POST':
        p.delete()
        
        
        
        return redirect('/myapp/products')
    
    
    return render(request,'myapp/delete_products.html',context=context)
    
    
    
    
    
    
    
    
    
    

users/views.py
from django.shortcuts import render,redirect

from users.forms import NewUserForm
from django.contrib.auth.decorators import login_required
from .models import Profile 


def register(request):
    
    if request.method == 'POST':
        form = NewUserForm(request.POST)
        print(f'form valid : {form.is_valid()}')
        if form.is_valid():
            form.save()
            
            
        return redirect('/myapp/products')
    form = NewUserForm(request.POST)    
    context = {
        'form' : form,
    }
    
    return render(request,'users/register.html ',context)


def profile(request):
    pro = Profile.objects.get(user=request.user)
    
    context = {'profile': pro}
    return render(request,'users/profile.html',context=context)


def create_profile(request):
    if request.method == 'POST':
        contact_number = request.POST.get('contact_number')
        image = request.FILES['upload']
        pro = Profile()
        pro.contact_number = contact_number
        pro.image = image
        pro.user = request.user
        pro.save()
        return redirect('/users/profile')
    
    return render(request,'users/createprofile.html')

myapp/templates/myapp/add_product.html
{% extends 'myapp/base.html' %} {% block contents %}

<h1 class="text-2xl font-bold m-10 text-green-500 ">➕ ADD Product</h1>
<form action="" method="POST" enctype="multipart/form-data" class='card-body w-2/6 shadow-xl m-10 p-10 bg-gray-100 bg-gradient-to-tr from-fuchsia-300 to-sky-500 '>
    {% csrf_token %}
    <div class="mb-5 ">
        <label class="block text-grey-700 text-sm font-bold mb-2">Product Name</label>
        <input class="input input-bordered w-full max-w-xs" type="text" name="name" id="name" placeholder="Name">
    </div>
    <div class="mb-5">
        <label class="block text-grey-700 text-sm font-bold mb-2">Product Price</label>
        <input class="input input-bordered w-full max-w-xs" type="text" name="price" id="price" placeholder="₹ price">
    </div>
    <div class="mb-5">
        <label class="block text-grey-700 text-sm font-bold mb-2">Product Description</label>
        <input class="input input-bordered w-full max-w-xs" type="text" name="desc" id="desc" placeholder="Description">
    </div>
    <div class="mb-5">
        <label class="block text-grey-700 text-sm font-bold mb-2">Product Details</label>
        <input class="input input-bordered w-full max-w-xs" type="text" name="details" id="details" placeholder="Details">
    </div>
    <div class="mb-5">
        <label class="block text-grey-700 text-sm font-bold mb-2">Product image</label>
        <input type="file" name="upload" id="upload">
    </div>
    <div>
        <input class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800 w-2/5" type="submit" accept="image/*"
            name="Add Product" value="Add Product">
    </div>
</form>
{% endblock %}

myapp/templates/myapp/base.html
<!-- {% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en" data-theme="light">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% tailwind_css %}
</head>

<body>
    {% block content%}
    <section>
        <div class="navbar bg-base-100 drop-shadow-md ">
            <div class="flex-1 navbar navbar bg-primary text-primary-content rounded-lg">
                <a class="btn btn-ghost normal-case text-xl ">
                    <b>CAM CARE</b></a>

            </div>
            <div class="flex-none">
                <div class="dropdown dropdown-end">
                    <label tabindex="0" class="btn btn-ghost btn-circle">
                  <div class="indicator">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-2.293 2.293c-.63.63-.184 1.707.707 1.707H17m0 0a2 2 0 100 4 2 2 0 000-4zm-8 2a2 2 0 11-4 0 2 2 0 014 0z" /></svg>
                    <span class="badge badge-sm indicator-item">0</span>
                  </div>
                </label>
                    <div tabindex="0" class="mt-3 card card-compact dropdown-content w-52 bg-base-100 shadow">
                        <div class="card-body">
                            <span class="font-bold text-lg">0 Items</span>
                            <span class="text-info">Subtotal:₹0</span>
                            <div class="card-actions">
                                <button class="btn btn-warning btn-block">View cart</button>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="dropdown dropdown-end">
                    <label tabindex="0" class="btn btn-ghost btn-circle avatar">
                  <div class="w-10 rounded-full">
                    <img src="https://placeimg.com/80/80/people" />
                  </div>
                </label>
                    <ul tabindex="0" class="menu menu-compact dropdown-content mt-3 p-2 shadow bg-base-100 rounded-box w-52 ">
                        <li>
                            <a class="justify-between">
                      Profile
                      <span class="badge btn-error ">New</span>
                    </a>
                        </li>
                        <li><a>Settings</a></li>
                        {% if user.is_authenticated %}
                        <li class="text-red-500"><a href="{% url 'users:logout' %}">Logout</a></li>
                        {% else %}
                        <li class="text-blue-500"> <a href="{% url 'users:login' %}">login</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </section>


    {% endblock %}



</body>

</html> -->
{% load tailwind_tags %}
<!DOCTYPE html>
<html data-theme="light">

<head>
    <meta charset=" utf-8 ">
    <meta http-equiv="X-UA-Compatible " content="IE=edge ">
    <title>Products</title>
    <meta name="description " content=" ">
    <meta name="viewport " content="width=device-width, initial-scale=1 ">
    <link rel="stylesheet " href=" "> {% tailwind_css %}
</head>

<body>
    <div class="navbar h-50 bg-base-100 drop-shadow-md ">
        <a class="btn btn-ghost normal-case text-xl ">
            <b>CAM CARE</b></a>
        <div class="flex-1 navbar flex-row-reverse  bg-primary text-primary-content rounded-lg">


        </div>
        <div class="flex-none">
            <div class="dropdown dropdown-end">
                <label tabindex="0" class="btn btn-ghost btn-circle">
              <div class="indicator">
                <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-2.293 2.293c-.63.63-.184 1.707.707 1.707H17m0 0a2 2 0 100 4 2 2 0 000-4zm-8 2a2 2 0 11-4 0 2 2 0 014 0z" /></svg>
                <span class="badge badge-sm indicator-item">0</span>
              </div>
            </label>
                <div tabindex="0" class="mt-3 card  dropdown-content w-43 bg-base-100 shadow">
                    <div class="card-body">
                        <span class="font-bold text-lg">0 Items</span>
                        <span class="text-info">Subtotal:₹0</span>
                        <div class="card-actions">
                            <button class="btn btn-warning btn-block">View cart</button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="dropdown dropdown-end ">
                <label tabindex="0" class="btn btn-ghost btn-circle avatar">
              <div class="w-10 rounded-full">
                <img src="https://placeimg.com/80/80/people" />
              </div>
            </label>
                <ul tabindex="0" class="menu menu-compact dropdown-content mt-3 p-2 shadow bg-base-100 rounded-box  ">
                    <li>
                        <a class="justify-between">
                  Profile
                  <span class="badge btn-error ">New</span>
                </a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="text-red-500"><a href="{% url 'users:logout' %}">Logout</a></li>
                    {% else %}
                    <li class="text-blue-500"> <a href="{% url 'users:login' %}">login</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
    {% block contents %}{% endblock %}

</body>

</html>

myapp/templates/myapp/delete_products.html
{% extends 'myapp/base.html' %} {% block contents %}

<h1 class="text-2xl font-bold m-10 text-green-500 ">🗑️ DELETE Product</h1>
<form action="" method="POST" enctype="multipart/form-data" class='card-body w-2/6 shadow-xl m-10 p-10 bg-gray-100 bg-gradient-to-tr from-fuchsia-300 to-sky-500 '>
    {% csrf_token %}
    <div class="mb-5 ">
        <label class="block text-grey-700 text-sm font-bold mb-2">Product Name:{{p.name}}</label>

    </div>
    <div class="mb-5">
        <label class="block text-grey-700 text-sm font-bold mb-2">Product Price:{{p.price}}</label>

    </div>
    <div class="mb-5">
        <label class="block text-grey-700 text-sm font-bold mb-2">Product Description:{{p.description}}</label>

    </div>

    <div class="mb-5">
        <label class="block text-grey-700 text-sm font-bold mb-2">Product image:{{p.image}}</label>
        <img class="w-36 mb-3 rounded-lg" src="{{p.image.url}}" alt="image not found">

    </div>
    <div>
        <input class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800 w-2/5" type="submit" accept="image/*"
            name="delete Product" value="delete Product">
    </div>
</form>
{% endblock %}

myapp/templates/myapp/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>index</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="css/style.css" rel="stylesheet">
</head>

<body>
    <h1 style="color:brown ;"> <b> Hello World</b></h1>
    <h2>This is me new myapp html code</h2>


    {% for i in li %}
    <h1 style="color:blue ;">{{i}}</h1>
    {% endfor %}

</body>

</html>

myapp/templates/myapp/products.html
{% extends "myapp/base.html"%} {% block contents%}


<div class="flex flex-wrap md:flex-wrap-reverse  justify-center  overflow-auto  ">
    {% for p in products %}

    <div class="card w-96 bg-base-96  p-4 border-4 shadow-xl rounded-lg">
        <a href="{% url 'myapp:products_details' p.id %} ">
            <figure class="px-10 pt-10">
                <img class="object-contain h-48 w-96 max-w-xs hover:scale-110 transition duration-300 ease-in-out .h-auto " src="{{p.image.url}}" alt="image is loading" />
            </figure>
            <div class="card-body items-center text-center">
                <h1 class="card-title" style=" text-align:center">
                    <b>{{p.name}}</b></h1>
                <p>{{p.description}}</p>

                <div class="card-actions justify-end">
                    <span class="text-3xl font-bold text-black ">₹{{p.price}}</span>
                    <button class="btn btn-warning ">add to cart</button>
                </div>

            </div>
        </a>
    </div>

    {% endfor %} {% endblock%}
</div>






<!-- </body>

</html> -->

myapp/templates/myapp/products_details.html
{% extends 'myapp/base.html' %} {% block contents %}


<div class="card  shadow-xl">
    <figure> <img class="  max-w-xs   hover:scale-110 transition duration-300 ease-in-out .h-auto " src="{{p.image.url}}" alt="image is loading" /></figure>
    <div class="card-body">
        </h1 class="card-title" style=" text-align:center">
        <b>{{p.name}}</b></h1>
        <p>{{p.description}}</p>
        <p>{{p.details}}</p>
        <div class="text-green-600">Sold By : {{p.seller}} </div>
        <a href="{% url 'users:sellerprofile' p.seller.id %}">
            <div class="text-sm">seller details</div>
        </a>

        <div class="card-actions justify-end">
            <span class="text-3xl font-bold text-black ">₹{{p.price}}</span>
            <button class="btn btn-primary ">BUY</button>
            <button class="btn btn-warning ">add to cart</button>
        </div>
    </div>
</div>

{% endblock %}

myapp/templates/myapp/update_product.html
{% extends 'myapp/base.html' %} {% block contents %}

<h1 class="text-2xl font-bold m-10 text-green-500 ">➕ UPDATE Product</h1>
<form action="" method="POST" enctype="multipart/form-data" class='card-body w-2/6 shadow-xl m-10 p-10 bg-gray-100 bg-gradient-to-tr from-fuchsia-300 to-sky-500 '>
    {% csrf_token %}
    <div class="mb-5 ">
        <label class="block text-grey-700 text-sm font-bold mb-2">Product Name</label>
        <input class="input input-bordered w-full max-w-xs" type="text" name="name" value="{{p.name}}" id="name" placeholder="Name">
    </div>
    <div class="mb-5">
        <label class="block text-grey-700 text-sm font-bold mb-2">Product Price</label>
        <input class="input input-bordered w-full max-w-xs" type="text" name="price" id="price" value="{{p.price}}" placeholder="₹ price">
    </div>
    <div class="mb-5">
        <label class="block text-grey-700 text-sm font-bold mb-2">Product Description</label>
        <input class="input input-bordered w-full max-w-xs" type="text" name="desc" id="desc" value="{{p.description}}" placeholder="Description">
    </div>
    <div class="mb-5">
        <label class="block text-grey-700 text-sm font-bold mb-2">Product Details</label>
        <input class="input input-bordered w-full max-w-xs" type="text" name="desc" id="desc" value="{{p.details}}" placeholder="details">
    </div>
    <div class="mb-5">
        <label class="block text-grey-700 text-sm font-bold mb-2">Product image</label>
        <img class="w-36 mb-3 rounded-lg" src="{{p.image.url}}" alt="image not found">
        <input type="file" name="upload" id="upload">
    </div>
    <div>
        <input class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800 w-2/5" type="submit" accept="image/*"
            name="update Product" value="update Product">
    </div>
</form>
{% endblock %}

theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-gray-50 font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>

users/templates/users/createprofile.html
{% extends "myapp/base.html" %} {% block contents %}
<h1 class="text-2xl font-bold m-10">➕ CREATE PROFILE</h1>
<form class='card w-2/6 shadow-2xl m-10 p-10 bg-gray-100 bg-gradient-to-tr from-fuchsia-300 to-sky-500' method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-5">
        <label class="block text-grey-700 text-sm font-bold mb-2">Contact Number</label>
        <input type="text" name="contact_number" placeholder="number" id="contact_number">
    </div>
    <div class="mb-5">
        <label class="block text-grey-700 text-sm font-bold mb-2">Upload Your Profile Picture</label>
        <input type="file" name="upload" id="upload">
    </div>
    <div class="mb-5">
        <button class="btn">
            <input type="submit" accept="image/*" name="Add Product" value="Add Product">
        </button>
    </div>

</form>
{% endblock %}

users/templates/users/login.html
{% extends 'myapp/base.html' %} {% block contents %}
<form action="{% url 'users:login' %}" method="POST" class="h-screen">
    {% csrf_token %}
    <div class="container px-6 py-12 ">
        <div class="flex justify-center items-center flex-wrap h-full g-6 text-gray-800">
            <div class="md:w-8/12 lg:w-6/12 mb-12 md:mb-0">
                <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/draw2.svg" class="w-full" alt="Phone image" />
            </div>
            <div class="md:w-8/12 lg:w-5/12 lg:ml-20">
                <form>

                    <div class="mb-6">
                        <label for="email-address" class="sr-only">Email address</label>
                        <input type="text" id="id_username" name="username" required class="form-control block w-full px-4 py-2 text-xl font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none"
                            placeholder="Username" />
                    </div>


                    <div class="mb-6">
                        <label for="password" class="sr-only">Password</label>
                        <input type="password" id="id_password" name="password" required class="form-control block w-full px-4 py-2 text-xl font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none"
                            placeholder="Password" />
                    </div>

                    <div class="flex justify-between items-center mb-6">
                        <div class="form-group form-check">
                            <input type="checkbox" class="form-check-input appearance-none h-4 w-4 border border-gray-300 rounded-sm bg-white checked:bg-blue-600 checked:border-blue-600 focus:outline-none transition duration-200 mt-1 align-top bg-no-repeat bg-center bg-contain float-left mr-2 cursor-pointer"
                                id="exampleCheck3" checked />
                            <label class="form-check-label inline-block text-gray-800" for="exampleCheck2">Remember me</label
                >
              </div>
              <a
                href="#!"
                class="text-blue-600 hover:text-blue-700 focus:text-blue-700 active:text-blue-800 duration-200 transition ease-in-out"
                >Forgot password?</a
              >
            </div>
  
            <div>
            <button
              type="submit"
              class="inline-block px-7 py-3 bg-blue-600 text-white font-medium text-sm leading-snug uppercase rounded shadow-md hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out w-full"
              data-mdb-ripple="true"
              data-mdb-ripple-color="light"
            >
              Sign in
            </button>
        </div>
  
           
        </div>
      </div>
    </div>
</form>
{% endblock %}

users/templates/users/logout.html
{% extends 'myapp/base.html' %} {% block contents %}

<div class="card w-2/6 shadow-2xl m-10 p-10 bg-gray-100 bg-gradient-to-tr from-fuchsia-300 to-sky-500">
    <figure><img src="" alt="movie"></figure>
    <div class='card-body'>
        <h2 class="card-title">logging out</h2>
        <p>YOU HABE BEEN LOGOUT </p>
        <div class="card-actions justify-end">
            <button class="btn btn-primary">bye</button>
        </div>
    </div>

    {% endblock %}

users/templates/users/profile.html
{% extends 'myapp/base.html' %} {% block contents %}

<div class="card card-side bg-base=-100 shadow-xl">
    <figure><img src="{{profile.image.url}}" alt="loading"></figure>
    <div class="card-body">
        <h2 class="card-title">{{user.username}}</h2>
    </div>
</div>

{% endblock %}

users/templates/users/register.html
 {% extends 'myapp/base.html' %} {% block contents %}
<form style="position:relative; left: 470px; margin-top: 2%;" action="" method="POST" class='card w-2/6 shadow-2xl m-10 p-10 bg-gray-100 bg-gradient-to-tr from-fuchsia-300 to-sky-500'>
    {% csrf_token %}

    <h1 class="text-2xl font-bold text-center">👤Create An User Account</h1>
    <div class="mb-5">
        <label class="block text-grey-700 text-sm font-bold mb-2">Username</label> {{form.username}}
    </div>
    <div class="mb-5">
        <label class="block text-grey-700 text-sm font-bold mb-2">E Mail</label> {{form.email}}
    </div>
    <div class="mb-5">
        <label class="block text-grey-700 text-sm font-bold mb-2">Password</label> {{form.password1}}
    </div>
    <div class="mb-5">
        <label class="block text-grey-700 text-sm font-bold mb-2">Confirm Password</label> {{form.password2}}
    </div>
    <div class="mt-3">
        <button class="w-full px-6 py-2 mt-4 text-white bg-blue-600 rounded-lg hover:bg-blue-900" type="submit">Create Account</button>
    </div>
</form>




{%endblock%}